//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INGEMMET.GeocatminApp.Dominio.Entidades
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PagoVigencia", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
    public partial class PagoVigencia : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string sDAnio1Field;

        private string sDAnio2Field;

        private string sDAnio3Field;

        private string sDTotalField;

        private string sNombreField;

        private string sSAnio1Field;

        private string sSAnio2Field;

        private string sSAnio3Field;

        private string sSTotalField;

        private string sTipoField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDAnio1
        {
            get
            {
                return this.sDAnio1Field;
            }
            set
            {
                this.sDAnio1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDAnio2
        {
            get
            {
                return this.sDAnio2Field;
            }
            set
            {
                this.sDAnio2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDAnio3
        {
            get
            {
                return this.sDAnio3Field;
            }
            set
            {
                this.sDAnio3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDTotal
        {
            get
            {
                return this.sDTotalField;
            }
            set
            {
                this.sDTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNombre
        {
            get
            {
                return this.sNombreField;
            }
            set
            {
                this.sNombreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSAnio1
        {
            get
            {
                return this.sSAnio1Field;
            }
            set
            {
                this.sSAnio1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSAnio2
        {
            get
            {
                return this.sSAnio2Field;
            }
            set
            {
                this.sSAnio2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSAnio3
        {
            get
            {
                return this.sSAnio3Field;
            }
            set
            {
                this.sSAnio3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSTotal
        {
            get
            {
                return this.sSTotalField;
            }
            set
            {
                this.sSTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipo
        {
            get
            {
                return this.sTipoField;
            }
            set
            {
                this.sTipoField = value;
            }
        }
    }

}

namespace INGEMMET.GeocatminApp.Dominio
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IPagoVigencia")]
    public interface IPagoVigencia
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPagoVigencia/ListarPagoVigencia", ReplyAction = "http://tempuri.org/IPagoVigencia/ListarPagoVigenciaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(INGEMMET.GeocatminApp.Dominio.Entidades.Excepcion), Action = "http://tempuri.org/IPagoVigencia/ListarPagoVigenciaExcepcionFault", Name = "Excepcion", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
        INGEMMET.GeocatminApp.Dominio.Entidades.PagoVigencia[] ListarPagoVigencia(INGEMMET.GeocatminApp.Dominio.Entidades.PagoVigencia entPagoVigencia);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagoVigenciaChannel : IPagoVigencia, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagoVigenciaClient : System.ServiceModel.ClientBase<IPagoVigencia>, IPagoVigencia
    {

        public PagoVigenciaClient()
        {
        }

        public PagoVigenciaClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public PagoVigenciaClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PagoVigenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PagoVigenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public INGEMMET.GeocatminApp.Dominio.Entidades.PagoVigencia[] ListarPagoVigencia(INGEMMET.GeocatminApp.Dominio.Entidades.PagoVigencia entPagoVigencia)
        {
            return base.Channel.ListarPagoVigencia(entPagoVigencia);
        }
    }
}