//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INGEMMET.GeocatminApp.Dominio.Entidades
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Combos", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
    public partial class Combos : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ParametroField;

        private string nameField;

        private string valueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parametro
        {
            get
            {
                return this.ParametroField;
            }
            set
            {
                this.ParametroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}


namespace INGEMMET.GeocatminApp.Dominio
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICombos")]
    public interface ICombos
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICombos/SelListarHojas", ReplyAction = "http://tempuri.org/ICombos/SelListarHojasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(INGEMMET.GeocatminApp.Dominio.Entidades.Excepcion), Action = "http://tempuri.org/ICombos/SelListarHojasExcepcionFault", Name = "Excepcion", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
        INGEMMET.GeocatminApp.Dominio.Entidades.Combos[] SelListarHojas(INGEMMET.GeocatminApp.Dominio.Entidades.Combos entHojas);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICombos/SelListarUbigeo", ReplyAction = "http://tempuri.org/ICombos/SelListarUbigeoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(INGEMMET.GeocatminApp.Dominio.Entidades.Excepcion), Action = "http://tempuri.org/ICombos/SelListarUbigeoExcepcionFault", Name = "Excepcion", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
        INGEMMET.GeocatminApp.Dominio.Entidades.Combos[] SelListarUbigeo(INGEMMET.GeocatminApp.Dominio.Entidades.Combos entUbigeo);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICombosChannel : ICombos, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CombosClient : System.ServiceModel.ClientBase<ICombos>, ICombos
    {

        public CombosClient()
        {
        }

        public CombosClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CombosClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CombosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CombosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public INGEMMET.GeocatminApp.Dominio.Entidades.Combos[] SelListarHojas(INGEMMET.GeocatminApp.Dominio.Entidades.Combos entHojas)
        {
            return base.Channel.SelListarHojas(entHojas);
        }

        public INGEMMET.GeocatminApp.Dominio.Entidades.Combos[] SelListarUbigeo(INGEMMET.GeocatminApp.Dominio.Entidades.Combos entUbigeo)
        {
            return base.Channel.SelListarUbigeo(entUbigeo);
        }
    }
}