//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INGEMMET.GeocatminApp.Dominio.Entidades
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Catastro", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
    public partial class Catastro : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CALIFICACIONField;

        private string CARTAField;

        private string CODIGOUField;

        private string DECICION_DE_TITULACIONField;

        private string DECISION_EXTINCIONField;

        private string DEPARTAMENTOField;

        private string DERECHO_MINEROField;

        private string DIRECCIONField;

        private string DISTRITOField;

        private string ESTADOField;

        private string FECHA_RES_EXTINCIONField;

        private string FECHA_RES_TITULOField;

        private string FORMULACIONField;

        private string HECTAREAField;

        private string HORA_FORMULACIONField;

        private string PROVINCIAField;

        private string ParametroField;

        private string RESOLUCION_EXTINCIONField;

        private string RESOLUCION_TITULOField;

        private string SUSTANCIAField;

        private string TIPOField;

        private string TITULAR_REFERENCIALField;

        private string UBICACION_EXPEDIENTEField;

        private string ZONAField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALIFICACION
        {
            get
            {
                return this.CALIFICACIONField;
            }
            set
            {
                this.CALIFICACIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CARTA
        {
            get
            {
                return this.CARTAField;
            }
            set
            {
                this.CARTAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOU
        {
            get
            {
                return this.CODIGOUField;
            }
            set
            {
                this.CODIGOUField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DECICION_DE_TITULACION
        {
            get
            {
                return this.DECICION_DE_TITULACIONField;
            }
            set
            {
                this.DECICION_DE_TITULACIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DECISION_EXTINCION
        {
            get
            {
                return this.DECISION_EXTINCIONField;
            }
            set
            {
                this.DECISION_EXTINCIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO
        {
            get
            {
                return this.DEPARTAMENTOField;
            }
            set
            {
                this.DEPARTAMENTOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DERECHO_MINERO
        {
            get
            {
                return this.DERECHO_MINEROField;
            }
            set
            {
                this.DERECHO_MINEROField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION
        {
            get
            {
                return this.DIRECCIONField;
            }
            set
            {
                this.DIRECCIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRITO
        {
            get
            {
                return this.DISTRITOField;
            }
            set
            {
                this.DISTRITOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO
        {
            get
            {
                return this.ESTADOField;
            }
            set
            {
                this.ESTADOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_RES_EXTINCION
        {
            get
            {
                return this.FECHA_RES_EXTINCIONField;
            }
            set
            {
                this.FECHA_RES_EXTINCIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_RES_TITULO
        {
            get
            {
                return this.FECHA_RES_TITULOField;
            }
            set
            {
                this.FECHA_RES_TITULOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FORMULACION
        {
            get
            {
                return this.FORMULACIONField;
            }
            set
            {
                this.FORMULACIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HECTAREA
        {
            get
            {
                return this.HECTAREAField;
            }
            set
            {
                this.HECTAREAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HORA_FORMULACION
        {
            get
            {
                return this.HORA_FORMULACIONField;
            }
            set
            {
                this.HORA_FORMULACIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROVINCIA
        {
            get
            {
                return this.PROVINCIAField;
            }
            set
            {
                this.PROVINCIAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parametro
        {
            get
            {
                return this.ParametroField;
            }
            set
            {
                this.ParametroField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESOLUCION_EXTINCION
        {
            get
            {
                return this.RESOLUCION_EXTINCIONField;
            }
            set
            {
                this.RESOLUCION_EXTINCIONField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESOLUCION_TITULO
        {
            get
            {
                return this.RESOLUCION_TITULOField;
            }
            set
            {
                this.RESOLUCION_TITULOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUSTANCIA
        {
            get
            {
                return this.SUSTANCIAField;
            }
            set
            {
                this.SUSTANCIAField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO
        {
            get
            {
                return this.TIPOField;
            }
            set
            {
                this.TIPOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITULAR_REFERENCIAL
        {
            get
            {
                return this.TITULAR_REFERENCIALField;
            }
            set
            {
                this.TITULAR_REFERENCIALField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UBICACION_EXPEDIENTE
        {
            get
            {
                return this.UBICACION_EXPEDIENTEField;
            }
            set
            {
                this.UBICACION_EXPEDIENTEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZONA
        {
            get
            {
                return this.ZONAField;
            }
            set
            {
                this.ZONAField = value;
            }
        }
    }

}

namespace INGEMMET.GeocatminApp.Dominio
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICatastro")]
    public interface ICatastro
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICatastro/SelListarCatastro", ReplyAction = "http://tempuri.org/ICatastro/SelListarCatastroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(INGEMMET.GeocatminApp.Dominio.Entidades.Excepcion), Action = "http://tempuri.org/ICatastro/SelListarCatastroExcepcionFault", Name = "Excepcion", Namespace = "http://schemas.datacontract.org/2004/07/INGEMMET.GeocatminApp.Dominio.Entidades")]
        INGEMMET.GeocatminApp.Dominio.Entidades.Catastro[] SelListarCatastro(INGEMMET.GeocatminApp.Dominio.Entidades.Catastro entCatastro);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatastroChannel : ICatastro, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatastroClient : System.ServiceModel.ClientBase<ICatastro>, ICatastro
    {

        public CatastroClient()
        {
        }

        public CatastroClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CatastroClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CatastroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CatastroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public INGEMMET.GeocatminApp.Dominio.Entidades.Catastro[] SelListarCatastro(INGEMMET.GeocatminApp.Dominio.Entidades.Catastro entCatastro)
        {
            return base.Channel.SelListarCatastro(entCatastro);
        }
    }
}